os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - git
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - mkdir fox && cd fox
  - git clone https://gitlab.com/OrangeFox/misc/scripts
  - cd scripts
  - bash setup/android_build_env.sh
  - bash setup/install_android_sdk.sh
  - cd .. && rsync rsync://sources.orangefox.download/sources/fox_10.0 . --progress -a
  - cd fox_10.0 && cd device
  - rm -rf xiaomi
  - git clone https://github.com/AnR-Lin/Infinix_X682B_TWRP_TREE Infinix/X682B/
  - cd ..
  - source build/envsetup.sh
  - export ALLOW_MISSING_DEPENDENCIES=true
  - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
  - export LC_ALL="C"
  - export OF_VANILLA_BUILD=1
  - lunch omni_X682B-eng && mka recoveryimage
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    repo: AnR-Lin/Infinix_X682B_TWRP_TREE # Optional: If you want to deploy on different repository
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
